### ISSUE TITLE
Token is expired

### ISSUE THREAD

**Issue by MoKhajavi75** [SamadiPour/bonbast#19]
Hey

I guess we have an issue:

```bash
~/Desktop ❯ bonbast
Error: token is expired. Try again later.
```

**Comment by MaminHakim** [comment]
update the project

**Comment by SamadiPour** [comment]
Update to the latest version.
```
pip3 install -U bonbast
```

**Comment by hzonuz** [comment]
But it does't work with homebrew.

**Comment by SamadiPour** [comment]
@hzonuz The issue shouldn't be related to homebrew. I'm currently using it with homebrew myself. Does it work with Python for you?
Also, your IP might be blocked.

**Comment by hzonuz** [comment]
No, it seems doesn't work. I don't think that my ip is blocked. Maybe it caches sth at the first time.
