### ISSUE TITLE
403 Client Error: Forbidden for url: https://bonbast.com/

### ISSUE THREAD

**Issue by hmralavi** [SamadiPour/bonbast#29]
I'm using a github action cronjob to get prices every 15 minutes.
I'm using this piece of code to get the prices:
```python
import bonbast.main

collections = bonbast.main.get_prices()
prices = []
for collection in collections:
    for model in collection:
        try:
            prices.append([model.code, model.sell])
        except AttributeError:
            prices.append([model.code, model.price])
print(prices)

```

it works well on my machine. But on github actions, sometime it works fine and sometimes i get the error `403 Client Error: Forbidden for url: https://bonbast.com/`.

I guess bonbast server blocks the requests sometimes. the reason migh be due to USER_AGENT definition:
`USER_AGENT = ('Mozilla/5.0 (Linux; Android 13; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) '
              'Chrome/120.0.0.0 Mobile Safari/537.36')`

Do you think setting up a random USER_AGENT might fix the issue? something like this:

```python
import requests
import random

user_agents_list = [
    'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'
]

r = requests.get('https://bonbast.com/`, headers={'User-Agent': random.choice(user_agents_list)})
```

**Comment by SamadiPour** [comment]
I don't think it's because of the User-Agent. As far as I know, it's because of the IP. GitHub has a limited number of IPs assigned to Codespace/Workflow machines, and those are banned in Bonbast. Try using a personal/paid proxy.
